### ISSUE TITLE
Build failure with QT 5.5.1 on Mac OS

### ISSUE THREAD

**Issue by mikeage** [chasonr/nethack-3.6.0-patches#3]
I'm not sure if the build is supposed to work with QT5, but the hints file does say:

"set QTDIR either here or in the environment to point to the Qt4 or Qt5"

In any case, when setting QTDIR to /usr/local/Cellar/qt5/5.5.1_2/ (installed via homebrew), I get the attached errors
[qt5_failure.txt](https://github.com/chasonr/nethack-3.6.0-patches/files/76482/qt5_failure.txt)

FWIW, I don't consider this a high priority issue, as QT4 works, and seems to still be more popular than QT5.

**Comment by chasonr** [comment]
Every version of Qt has a program called "moc", which performs some magic on the headers and generates another header. The errors indicate that the source files are trying to include the output of a moc from Qt 4.
I don't see where the moc is being run. Does "make spotless" and then trying again clear this up? If not, then that's the problem.
It is supposed to work with Qt 5. I'm presently working on the Windows version and I have both 4 and 5 handy.

**Comment by mikeage** [comment]
Ah... I didn't know about make spotless. I only ran make clean. After a make spotless, this worked (a problem with the link, but I think it's homebrew related; I'll figure it out on my own).

Closing...
